server:
  port: 8080

spring:
#  datasource:
#    url: jdbc:postgresql://192.168.3.13:54321/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 200
#      minimum-idle: 100
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      max-lifetime: 30000
#      connection-timeout: 10000
#      connection-test-query: SELECT 1
#      read-only: false
#      validation-timeout: 3000
#      login-timeout: 5
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: customers-group
      enable-auto-commit: true
      auto-commit-interval: 100
    producer:
      bootstrap-servers: 192.168.3.13:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: customers-client
      batch.size: 16384
      properties:
        max.request.size: 52428800
#      buffer-memory: 10485760‬
    template:
      default-topic: customer_new10
#  cloud:
#    stream:
#      bindings:
#        demo_output:
#          destination: customers_new
#          group: customers_producer
  batch:
    initialize-schema: always
    job:
      enabled: true

#spring.kafka.producer.buffer-memory: 10485760‬